name: "wiz-cli"

on:
  pull_request:

jobs:
  wiz-cli-image-scan:
    name: "Wiz CLI Image Scan"
    runs-on: ubuntu-latest

    env:
      SCAN_PATH: "."
      TAG: "wiz-image-${{ github.sha }}"
      POLICY: "Default vulnerabilities policy"

    defaults:
      run:
        shell: bash

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: |
          cd $SCAN_PATH
          docker build -t $TAG .

      # Download Wiz CLI
      - name: Download Wiz CLI
        run: |
          curl -L -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
          chmod +x wizcli

      - name: Scan Docker Image
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: |
          ./wizcli scan container-image $TAG \
            --policy "$POLICY" \
            --id $WIZ_CLIENT_ID \
            --secret $WIZ_CLIENT_SECRET \
            --exit-code-on-failure

      # Optional: Tag image
      - name: Tag image (Graph enrichment)
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: |
          ./wizcli tag $TAG \
            --id $WIZ_CLIENT_ID \
            --secret $WIZ_CLIENT_SECRET
